sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
branches:
  only:
    - master
    - production
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.4.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.5.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.6.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.8.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.1.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.2.0"
notifications:
  email: false
addons:
  code_climate:
    repo_token: adf08323...
